twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['form/tailwind_css_form_theme.html.twig'] # Ajoutez le chemin ici
when@test:
    twig:
        strict_variables: true
